#information about the robot

# PCB communication
PCB_BRIDGE_UART_PORT: "/dev/ttyS0"
PCB_BRIDGE_CHECK_INTERVAL_MS: 40
MOTOR_MAX_SPEED_METER_SEC: 0.6
MOTOR_MIN_SPEED_METER_SEC: 0.1

# Physical characteristics of the robot
# export TICK_METERS=3653
ticks_meter: 3653
BASE_WIDTH: 0.2

# Motor Drive configuration
PID_MIN: 10.0
PID_MAX: 700.0
PID_P: 50.0
PID_I: 200.0
PID_D: 2.0
ENCODER_MIN: -32768
ENCODER_MAX: 32767